package dames.entity;
// Generated 30-ene-2021 18:44:32 by Hibernate Tools 4.3.1



/**
 * Moviments generated by hbm2java
 */
public class Moviments  implements java.io.Serializable {


     private Integer id;
     private Partides partides;
     private int desde;
     private int capA;
     private int desdeOrigen;
     private int capAOrigen;

    public Moviments() {
    }

    public Moviments(Partides partides, int desde, int capA, int desdeOrigen, int capAOrigen) {
       this.partides = partides;
       this.desde = desde;
       this.capA = capA;
       this.desdeOrigen = desdeOrigen;
       this.capAOrigen = capAOrigen;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Partides getPartides() {
        return this.partides;
    }
    
    public void setPartides(Partides partides) {
        this.partides = partides;
    }
    public int getDesde() {
        return this.desde;
    }
    
    public void setDesde(int desde) {
        this.desde = desde;
    }
    public int getCapA() {
        return this.capA;
    }
    
    public void setCapA(int capA) {
        this.capA = capA;
    }
    public int getDesdeOrigen() {
        return this.desdeOrigen;
    }
    
    public void setDesdeOrigen(int desdeOrigen) {
        this.desdeOrigen = desdeOrigen;
    }
    public int getCapAOrigen() {
        return this.capAOrigen;
    }
    
    public void setCapAOrigen(int capAOrigen) {
        this.capAOrigen = capAOrigen;
    }




}


