package dames.entity;
// Generated 31-ene-2021 19:52:25 by Hibernate Tools 4.3.1



/**
 * Moviments generated by hbm2java
 */
public class Moviments  implements java.io.Serializable {


     private Integer id;
     private Partides partides;
     private int fila;
     private int columna;
     private int filaOrigen;
     private int columnaOrigen;

    public Moviments() {
    }

    public Moviments(Partides partides, int fila, int columna, int filaOrigen, int columnaOrigen) {
       this.partides = partides;
       this.fila = fila;
       this.columna = columna;
       this.filaOrigen = filaOrigen;
       this.columnaOrigen = columnaOrigen;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Partides getPartides() {
        return this.partides;
    }
    
    public void setPartides(Partides partides) {
        this.partides = partides;
    }
    public int getFila() {
        return this.fila;
    }
    
    public void setFila(int fila) {
        this.fila = fila;
    }
    public int getColumna() {
        return this.columna;
    }
    
    public void setColumna(int columna) {
        this.columna = columna;
    }
    public int getFilaOrigen() {
        return this.filaOrigen;
    }
    
    public void setFilaOrigen(int filaOrigen) {
        this.filaOrigen = filaOrigen;
    }
    public int getColumnaOrigen() {
        return this.columnaOrigen;
    }
    
    public void setColumnaOrigen(int columnaOrigen) {
        this.columnaOrigen = columnaOrigen;
    }




}


