package dames.entity;
// Generated 31-ene-2021 19:52:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Partides generated by hbm2java
 */
public class Partides  implements java.io.Serializable {


     private Integer id;
     private String data;
     private String guanyador;
     private Set movimentses = new HashSet(0);

    public Partides() {
    }

	
    public Partides(String data) {
        this.data = data;
    }
    public Partides(String data, String guanyador, Set movimentses) {
       this.data = data;
       this.guanyador = guanyador;
       this.movimentses = movimentses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }
    public String getGuanyador() {
        return this.guanyador;
    }
    
    public void setGuanyador(String guanyador) {
        this.guanyador = guanyador;
    }
    public Set getMovimentses() {
        return this.movimentses;
    }
    
    public void setMovimentses(Set movimentses) {
        this.movimentses = movimentses;
    }




}


